// Plain-language definitions — written for a reader with zero psephology background.
// Surfaced via the <Info> tooltip and the header Glossary overlay.
export type GlossaryEntry = { term: string; short: string; long: string }

export const GLOSSARY: GlossaryEntry[] = [
  { term: 'Vote share', short: 'Of every 100 votes, how many a party got.',
    long: 'Out of every 100 valid votes cast in a seat, how many went to a party. 40% vote share means 40 of every 100 voters chose it.' },
  { term: 'Margin', short: 'Votes the winner beat the runner-up by.',
    long: 'The plain number of votes separating the winner from the second-placed candidate.' },
  { term: 'Margin %', short: "Winner's lead as a % of votes — under 3% is a close seat.",
    long: "The winner's lead measured as a share of all votes cast. ~1–2% is a nail-biter, 20%+ is a landslide. We call anything under 3% a 'close seat'." },
  { term: 'Swing', short: "Change in a party's vote share between two elections.",
    long: "How much a party's vote share went up or down compared with the previous election. A +5% swing means it gained 5% of the vote since last time; −5% means it lost that much." },
  { term: 'Strike rate', short: 'Of seats contested, the share won.',
    long: 'Of the seats a party actually contested, the percentage it won. Winning 18 of 25 seats it stood in = a 72% strike rate. A wide footprint with a low strike rate means a party is spreading thin or playing spoiler.' },
  { term: 'Stronghold / safe seat', short: 'A seat one party keeps winning.',
    long: 'A seat the same party wins election after election. Safe to bank on — campaign resources are better spent elsewhere.' },
  { term: 'Swing seat', short: 'A seat that changes hands — where elections are decided.',
    long: 'A seat that flips between parties from election to election. These are where campaigns are won and lost, and where survey/targeting effort pays off most.' },
  { term: 'Seat flip', short: 'The winning party changed vs last time.',
    long: 'A seat whose winning party is different from the previous election — it "flipped" from one party to another.' },
  { term: 'Retention', short: 'Share of its seats a party held onto.',
    long: 'Of the seats a party was defending, the share it won again. Low retention means incumbency is working against it.' },
  { term: 'Flippability', short: 'A 0–100 score for how winnable a near-lost seat is.',
    long: 'Our score (0–100) for how realistically a party could win a seat it narrowly lost. A closer loss, an improving trend, and recent by-poll or Lok-Sabha leads in that seat all push the score up. It is a guide, not a forecast.' },
  { term: 'Friendly fight', short: 'Allies running against each other, splitting their vote.',
    long: 'When parties that are supposed to be in the same alliance still put up candidates against one another in a seat — splitting votes that, combined, might have won it.' },
  { term: 'Alliance pooling ("what if")', short: 'Add allies’ votes together and re-decide the seat.',
    long: 'A what-if: we add up every allied candidate’s votes in a seat as if the alliance had fielded just one candidate, then see who would have won. It shows the cost of friendly fights.' },
  { term: 'Vote transfer (Assembly → Lok Sabha)', short: 'Do a party’s voters stick with it across election types?',
    long: 'Whether the people who vote for a party in the state assembly election also vote for it in the national (Lok Sabha) election, in the same area. A party can be strong in state polls but leak votes nationally, or vice-versa.' },
  { term: 'By-poll (bypoll)', short: 'A one-off election for a single vacant seat.',
    long: 'A standalone election held mid-term to fill one seat that fell vacant — because the sitting member died, resigned, or was disqualified. By-polls are an early read on which way the wind is blowing.' },
  { term: 'Hold rate', short: 'How often by-poll seats stay with the same party.',
    long: 'Across by-polls, how often the party that already held the seat managed to keep it. A hold rate below 50% means seats are slipping — the ground is moving.' },
  { term: 'Turnout', short: 'Share of registered voters who voted.',
    long: 'Of everyone eligible and registered to vote in a seat, the percentage who actually cast a ballot.' },
  { term: 'NOTA', short: '"None Of The Above" ballot option.',
    long: 'A button on the ballot to formally reject every candidate. Introduced in India from 2013 onward.' },
  { term: 'Reservation (GEN / SC / ST)', short: 'Some seats are reserved for SC/ST communities.',
    long: 'Certain seats can only be contested by candidates from Scheduled Castes (SC) or Scheduled Tribes (ST), to guarantee representation. The rest are General (GEN), open to all.' },
  { term: 'Delimitation', short: 'Redrawing seat boundaries — breaks comparisons.',
    long: 'The periodic redrawing of constituency boundaries to reflect population change. Across a redraw the old and new seats are not the same, so we never compute swing or flips through one.' },
  { term: 'EVM-only (2024 segments)', short: '2024 segment shares exclude postal votes.',
    long: 'For 2024, the assembly-segment vote shares are counted from EVMs (voting machines) only, leaving out postal ballots — so they read very slightly lower than the full totals.' },
  { term: 'Assembly (AE) vs Lok Sabha (GE)', short: 'State election vs national election.',
    long: 'AE = Assembly Election, which picks the state government and its MLAs. GE = General Election, which picks the national parliament and its MPs. People often vote differently in the two.' },
  { term: 'Alliance (NDA / INDIA / pre-poll)', short: 'Parties that agree to back each other before polling.',
    long: 'A group of parties that agree, before the election, to support each other and share seats. We label each candidate by the alliance they belonged to on polling day.' },
]

export const glossaryShort = (term: string) => GLOSSARY.find(g => g.term.toLowerCase().startsWith(term.toLowerCase()))?.short ?? ''
